In [16]:
import numpy as np
import commpy.channelcoding.gfields as gf
import commpy.channelcoding as cc

In [2]:
datos=np.arange(8)
print(datos)

m=3

[0 1 2 3 4 5 6 7]


In [3]:
x=gf.GF(datos,m)

In [4]:
x.elements

array([0, 1, 2, 3, 4, 5, 6, 7])

In [5]:
x.prim_poly

11

In [8]:
x.elements[1]+x.elements[-1]

8

In [17]:
cc.cyclic_code_genpoly(7,4)

array([13, 11])