# Códigos Cíclicos

### Ing. Pablo De Césare

In [1]:
import numpy as np
import CyclicCode as cc

- Son un subtipo de códigos lineales
- A todas las propiedades de linealidad, le agregan la del dezplazamiento cíclico
- Son altamente estructurados, faciles y eficientes de codificar
- Se representan a través de polinomios (la linealidad es heredada del álgebra de polinomios)

$$ V(x)=v_0.x^0+v_1.x^1+v_2.x^2 $$

### Dezplazamiento en j posiciones

Queremos lograr una estructura para el dezplazamiento en j posiciones de este tipo:

$$ V(x)=v_{n-j}.x^0+v_{n-j+1}.x^1+v_{n-j+2}.x^2+....+v_0.x^j+v_1.x^{j+1}+v_2.x^{j+2}....+..v_{n-j-1}.x^{n-1} $$

Para lograrlo, probamos con multiplicar por $$ x^j $$

de esta manera

$$ x^j.v(x)=v_0.x^j+v_1.x^{j+1}+...+v_{n-j-1}.x^{n-1}+v_{n-j}.x^n+...+v_{n-1}.x^{n+j-1} $$

se puede demostrar que se obtiene la rotacion si

$$ v^j(x) = resto .\frac{x^j.v(x)}{1+x^n} = x^j.v(x) mod (1+x^n) $$

## Ej sklar 6.7
Desplazar 3 lugares el codigo 1101

Solucion

La representacion polinomica de la palabra 1101 es:
$$ v(x)= 1+x+x^3 $$
n=4

$$ x^3 . (1+x+x^3) mod (x^4+1) $$
$$ (x^3+x^4+x^6) mod (x^4+1) $$


In [2]:
v=np.array([1,1,0,1]) 
cc.shift(v,3)

array([1, 0, 1, 1])

## Teorema

v(x) es una palabra de codigo si y solo si v es multiplo del g(x) (el polinomio generador!!)

g(x) es un factor de $$ 1+x^n $$


para las palabras de codigo de grado n g(x) va a tener grado $$n-k$$ (la redundancia!!)

## Codigo Ciclico

Polinomio generador $$ g(x) = 1 + x^2 + x^3 + x^4 $$

In [3]:
g = np.array([1,0,1,1,1]) # polinomio generador

miCod=cc.CyclicCode(g, 7)

# Codificación sistematica

Queremos arealizar una codificacion sistematica, es decir, que la palabra de codigo este formada por una parte del mensaje sin modificar y otra parte por la paridad.

$$ v(x)=x^{n-k}.u(x)+p(x) $$

Donde el termino $ x^{n-k}.u(x)$ representa a la palabra de codigo u(x) con n-k ceros atras y p(x) la paridad del mensaje.

Como $ v(x)=x^{n-k}.u(x)+p(x) $ es una palabra de codigo, entonces es un multiplo de g(x)

$$ v(x)=x^{n-k}.u(x)+p(x) = c(x).g(x) -> x^{n-k}.u(x) = c(x).g(x)+p(x) $$

tenemos el algoritmo de la division

$$ p(x) = resto{\frac{x^{n-k}.u(x)}{g(x)}} $$

Entonces codificamos como

$$ v(x)= x^{n-k}.u(x) + resto{\frac{x^{n-k}.u(x)}{g(x)}} $$

## Ej 1
codificar de forma sistematica el mensaje m=[1,0,1,1], con polinomio generador  g(x)=1+x+x^3


In [4]:
g = np.array([1,1,0,1]) # polinomio generador 1+x+x^3
m=np.array([1,0,1,1])
miCod=cc.CyclicCode(g, 7)

codeword=miCod.c(m)

print("la palabra de codigo es ",codeword)

la palabra de codigo es  [1 0 0 1 0 1 1]


Esta codificacion sistematica puede hacerse de maner muy eficiente con un circuito formado por registros de desplazamientos realimentados.

<img src='1.jpg' width="400" height="400">

## Decodificacion de la palabra de codigo y calculo de sindrome

El receptor recibe una palabra de código que pudo haber sido alterada por acción del canal de comunicación. Como toda palabra de código válida es múltiplo del polinomio generador g(x), el chequeo de error consta en verificar que el resto de la división.

Si el resto es cero, la palabra es válida y si da un valor distinto de cero, hubo un error en la cadena de transmisión.



In [5]:
syndrome=miCod.S(codeword)
print("el sindrome calculado ", syndrome)

el sindrome calculado  [0 0 0 0]


El chequeo de paridad, que también se implementa como una división, se hace de manera eficiente con registros de dezplazamiento.

<img src='2.jpg' width="400" height="400">

La mayoría de los códigos cíclicos se usan para chequeo de error y pedido de re-transmisión.
Pero como los códigos cíclicos, son también lineales, puede hallarse una matriz generadora G(x).

Se obtiene de codificar los elementos los mensajes que contienen solo un 1
para el ejemplo de C(7,4)
[0,0,0,1]
[0,0,1,0]
[0,1,0,0]
[1,0,0,0]


In [6]:
m4=np.array([0,0,0,1])
m3=np.array([0,0,1,0])
m2=np.array([0,1,0,0])
m1=np.array([1,0,0,0])

print("la matriz generadora es \n")
print(miCod.c(m1))
print(miCod.c(m2))
print(miCod.c(m3))
print(miCod.c(m4))

print("\n G(x)")
print(miCod.G())

print("\n H(x)")
print(miCod.H())

la matriz generadora es 

[1 1 0 1 0 0 0]
[0 1 1 0 1 0 0]
[1 1 1 0 0 1 0]
[1 0 1 0 0 0 1]

 G(x)
[[1 1 0 1 0 0 0]
 [0 1 1 0 1 0 0]
 [1 1 1 0 0 1 0]
 [1 0 1 0 0 0 1]]

 H(x)
[[1 0 0 1 0 1 1]
 [0 1 0 1 1 1 0]
 [0 0 1 0 1 1 1]]


In [7]:
## resumiendo ###

miCod.printInfo()


-> Linear Block Code Cb( 7 , 4 )
-> Message length (k):              4
-> Codeword length (n):             7
-> Coding rate (R = k/n):           0.5714285714285714
-> Minimum Distance (dmin):         3
-> Error Detection Capability:      2
-> Error Correction Capability (t): 1
-> Weight Distribution (A):         [0 0 7 7 0 0 1]
-> Generator Matrix (G):

[[1 1 0 1 0 0 0]
 [0 1 1 0 1 0 0]
 [1 1 1 0 0 1 0]
 [1 0 1 0 0 0 1]]

-> Parity Check Matrix (H):

[[1 0 0 1 0 1 1]
 [0 1 0 1 1 1 0]
 [0 0 1 0 1 1 1]]

-> Message Codeword Table:

Messages -> Codewords
[0 0 0 0] [0 0 0 0 0 0 0] m(X) = 0 	c(X) = 0
[1 0 0 0] [1 1 0 1 0 0 0] m(X) = 1 	c(X) = 1 + X + X^3
[0 1 0 0] [0 1 1 0 1 0 0] m(X) = X 	c(X) = X + X^2 + X^4
[1 1 0 0] [1 0 1 1 1 0 0] m(X) = 1 + X 	c(X) = 1 + X^2 + X^3 + X^4
[0 0 1 0] [1 1 1 0 0 1 0] m(X) = X^2 	c(X) = 1 + X + X^2 + X^5
[1 0 1 0] [0 0 1 1 0 1 0] m(X) = 1 + X^2 	c(X) = X^2 + X^3 + X^5
[0 1 1 0] [1 0 0 0 1 1 0] m(X) = X + X^2 	c(X) = 1 + X^4 + X^5
[1 1 1 0] [0 1 0 1 1 1 0] m