# Simulación de códigos lineales

### Ing. Pablo De Césare

In [1]:
import numpy as np
import LinearBlockCode as lc

In [2]:
miCod=lc.LinearBlockCode()

# Códigos lineales

Realizan una clase de control de paridad y pueden ser caracterizados por dos parámetros  n,k

- n -> numero de bits codificados
- k -> numero de bits del mesaje                   Con n>k

El mensaje de k-bits  -> 2^k vectores

El código de n-bits  -> 2^n vectores

El conjunto de 2n vectores  (tuplas) constituye un espacio vectorial sobre un campo binario de elementos 0 y 1.

Cada uno de los 2k códigos pueden ser descriptos por

#### U=m1.V1+m2.V2+m3.V3

m1,m2 y m3 terminan siendo las coordenadas la base Vn

Vn generaran las palabras de código a ser transmitidas 

### Codigo lineal (6,3)

En general hay una matriz G, generadora de dimensiones  (kxn)

ej:
<img src='1.jpeg' width="400" height="400">


In [3]:
g=[[1, 1, 0, 1, 0, 0], [0, 1, 1, 0, 1, 0], [1, 0, 1, 0, 0, 1]]
G=np.matrix(g)

miCod.setG(G)
miCod.G()

matrix([[1, 1, 0, 1, 0, 0],
        [0, 1, 1, 0, 1, 0],
        [1, 0, 1, 0, 0, 1]])

In [4]:
print("longitud de palabra de codigo = ",miCod.n())
print("longitud de la redundancia = ",miCod.k())
print("longitud del mensaje = ",miCod.n()-miCod.k())

longitud de palabra de codigo =  6
longitud de la redundancia =  3
longitud del mensaje =  3


## Codificar una palabra de código
<img src='2.jpeg' width="400" height="400">

In [5]:
msj=np.matrix([1,1,0])
codeword=miCod.c(msj)

print("la palabra de codigo generada es =",codeword)


la palabra de codigo generada es = [[1 0 1 1 1 0]]


## Codificacion sistematica
<img src='3.jpeg' width="400" height="400">

In [6]:
print("Matriz G \n\n",miCod.G())
print("\n")
print("Matriz P \n\n",miCod.P())

Matriz G 

 [[1 1 0 1 0 0]
 [0 1 1 0 1 0]
 [1 0 1 0 0 1]]


Matriz P 

 [[1 1 0]
 [0 1 1]
 [1 0 1]]


In [7]:
miCod.printMessageCodewordTable()

Messages -> Codewords (c = m ◦ G)
[0 0 0] [[0 0 0 0 0 0]]
[1 0 0] [[1 1 0 1 0 0]]
[0 1 0] [[0 1 1 0 1 0]]
[1 1 0] [[1 0 1 1 1 0]]
[0 0 1] [[1 0 1 0 0 1]]
[1 0 1] [[0 1 1 1 0 1]]
[0 1 1] [[1 1 0 0 1 1]]
[1 1 1] [[0 0 0 1 1 1]]


# Matriz de chequeo de paridad

Llamemos H a la matriz de chequeo de paridad que nos permitirá decodificar los vectores recibidos.

Para cada matriz G de dimensión (k x n) existe una matriz H de dimensión (n-k)x n y las filas de G son ortogonales a las filas de H tal que 

    G . H^T=0

Para satisfacer esa condición H tal que H=[I | P.T]

In [8]:
miCod.H()

matrix([[1, 0, 0, 1, 0, 1],
        [0, 1, 0, 1, 1, 0],
        [0, 0, 1, 0, 1, 1]])

Se verifica que cada código generado “U=m.G” cuando se multiplica por U.H^T=0  

## Chequeo del Sindrome

Del lado del receptor, recibimos una palabra de codigo + un cierto patron de error que corropio el mensaje original, tal que 

r=U+e

Se define "Sindrome" S a 

S = r . H^T

Si S=0 r es un código valido, por el contrario si S ≠0 está corrupto  


In [9]:
e1=np.matrix([1,0,0,0,0,0]) # error
e2=np.matrix([0,0,0,0,0,0]) # sin error
r1=codeword+e1
r2=codeword+e2


In [10]:
s1=miCod.s(r1)
print("sindrome 1 =",s1)
s2=miCod.s(r2)
print("sindrome 2 =",s2)

sindrome 1 = [[1 0 0]]
sindrome 2 = [[0 0 0]]


In [11]:
miCod.printSyndromeVectorEquations()



s0 = r0 ⊕ r3 ⊕ r5
s1 = r1 ⊕ r3 ⊕ r4
s2 = r2 ⊕ r4 ⊕ r5


In [12]:
miCod.correctableErrorPatterns()


array([[0, 0, 0, 0, 0, 0],
       [1, 0, 0, 0, 0, 0],
       [0, 1, 0, 0, 0, 0],
       [0, 0, 1, 0, 0, 0],
       [0, 0, 0, 1, 0, 0],
       [0, 0, 0, 0, 1, 0],
       [0, 0, 0, 0, 0, 1]])

In [13]:
miCod.printDecodingTable()



Correctable Error Patterns -> Syndromes
[0 0 0 0 0 0] [[0 0 0]]
[1 0 0 0 0 0] [[1 0 0]]
[0 1 0 0 0 0] [[0 1 0]]
[0 0 1 0 0 0] [[0 0 1]]
[0 0 0 1 0 0] [[1 1 0]]
[0 0 0 0 1 0] [[0 1 1]]
[0 0 0 0 0 1] [[1 0 1]]


In [14]:
ep=np.matrix([1,0,0,0,0,0])
s=miCod.s(ep)
print("sindrome =" + str(s)+ "error pathern"+str(ep))



sindrome =[[1 0 0]]error pathern[[1 0 0 0 0 0]]


Creamos un diccionario donde cada sindrome es un error pathern 

In [15]:
miCod.decodingTable()

{'[[0 0 0]]': array([0, 0, 0, 0, 0, 0]),
 '[[1 0 0]]': array([1, 0, 0, 0, 0, 0]),
 '[[0 1 0]]': array([0, 1, 0, 0, 0, 0]),
 '[[0 0 1]]': array([0, 0, 1, 0, 0, 0]),
 '[[1 1 0]]': array([0, 0, 0, 1, 0, 0]),
 '[[0 1 1]]': array([0, 0, 0, 0, 1, 0]),
 '[[1 0 1]]': array([0, 0, 0, 0, 0, 1])}

In [16]:
print("decodificado r1 = ",miCod.syndromeDecode(r1))
print("decodificado r2 = ",miCod.syndromeDecode(r2))
print("palabra de codigo original = ",codeword)

decodificado r1 =  [[1 0 1 1 1 0]]
decodificado r2 =  [[1 0 1 1 1 0]]
palabra de codigo original =  [[1 0 1 1 1 0]]


# Capacidad de detección y corrección de errores

- Se define w (peso de Hamming) al numero de elementos distintos de 0 de una palabra de código
- Se define d  (distancia de Hamming) al número de bits diferentes entre código y código

por las propiedades de la suma en modulo 2 y la linealidad del codigo, la suma de 2 palabras de código representa otra palabra de codigo.

La distancia de Hamming entre 2 palabras es igual al peso de la suma

#### d(U,V) = w(U+W)

Para hallarla no es necesario cualcular el peso de cada suma de palabras de codigo, solo el peso de cada palabra individual excluyendo al elemento cero
De forma equivalente, la dmin corresponde a la palabra con minima distancia a la palabra de codigo "cero" 

In [17]:
miCod.dminVerbose()

Empezamos con dmin = n
dmin =  6
Iteracion a traves de la tabla de palabras de codigo y comparacion de los pesos de cada vector
Vector  [[0 0 0 0 0 0]]  tiene un peso de  0
El peso de  [[1 1 0 1 0 0]]  es  3  <  6  actualizamos dmin, dmin =  3
Vector  [[0 1 1 0 1 0]]  tiene un peso de  3
Vector  [[1 0 1 1 1 0]]  tiene un peso de  4
Vector  [[1 0 1 0 0 1]]  tiene un peso de  3
Vector  [[0 1 1 1 0 1]]  tiene un peso de  4
Vector  [[1 1 0 0 1 1]]  tiene un peso de  4
Vector  [[0 0 0 1 1 1]]  tiene un peso de  3


La capacidad de deteccion de errores es igual a dmin-1

La capacidad de correccion t es igual

t= (dmin - 1)/2

In [18]:
miCod.errorDetectionCapability()

2

In [19]:
miCod.printInfo()

-> Linear Block Code Cb( 6 , 3 )
-> Message length (k):              3
-> Codeword length (n):             6
-> Coding rate (R = k/n):           0.5
-> Minimum Distance (dmin):         3
-> Error Detection Capability:      2
-> Error Correction Capability (t): 1
-> Weight Distribution (A):         [0 0 4 3 0 0]
-> Generator Matrix (G):

[[1 1 0 1 0 0]
 [0 1 1 0 1 0]
 [1 0 1 0 0 1]]

-> Parity Check Matrix (H):

[[1 0 0 1 0 1]
 [0 1 0 1 1 0]
 [0 0 1 0 1 1]]

-> Message Codeword Table:

Messages -> Codewords (c = m ◦ G)
[0 0 0] [[0 0 0 0 0 0]]
[1 0 0] [[1 1 0 1 0 0]]
[0 1 0] [[0 1 1 0 1 0]]
[1 1 0] [[1 0 1 1 1 0]]
[0 0 1] [[1 0 1 0 0 1]]
[1 0 1] [[0 1 1 1 0 1]]
[0 1 1] [[1 1 0 0 1 1]]
[1 1 1] [[0 0 0 1 1 1]]

-> Parity Check Equations:

c0 = m0 ⊕ m2
c1 = m0 ⊕ m1
c2 = m1 ⊕ m2
c3 = m0
c4 = m1
c5 = m2

-> Syndrome Vector Equations:

s0 = r0 ⊕ r3 ⊕ r5
s1 = r1 ⊕ r3 ⊕ r4
s2 = r2 ⊕ r4 ⊕ r5

-> Standard Array:

[[0 0 0 0 0 0]] | [[1 1 0 1 0 0]] [[0 1 1 0 1 0]] [[1 0 1 1 1 0]] [[1 0 1 0 0 1]] [[0